export default {
    CARD: "card"
    , FETCH_CARDS: "fetch cards"
    , FETCH_CARDS_SUCCESS: "fetch cards success"
    , FETCH_CARDS_FAILURE: "fetch cards failure"
    , TOGGLE_CARD_DETAILS: "toggle card details"
    , LOAD_DEFAULT_DRAFT: "load default draft"
    , CREATE_CARD: "create card"
    , CREATE_CARD_SUCCESS: "create card success"
    , CREATE_CARD_FAILURE: "create card failure"
    , UPDATE_CARD: "update card"
    , UPDATE_CARD_SUCCESS: "update card success"
    , UPDATE_CARD_FAILURE: "update card failure"
    , UPDATE_CARD_STATUS: "update card status"
    , UPDATE_CARD_POSITION: "update card position"
    , PERSIST_CARD_DRAG: "persist card drag"
    , PERSIST_CARD_DRAG_SUCCESS: "persist card drag success"
    , PERSIST_CARD_DRAG_FAILURE: "persist card drag failure"
    , CREATE_DRAFT: "create draft"
    , UPDATE_DRAFT: "update draft"
    , CREATE_TASK: "create task"
    , CREATE_TASK_SUCCESS: "create task success"
    , CREATE_TASK_FAILURE: "create task failure"
    , DELETE_TASK: "delete task"
    , DELETE_TASK_SUCCESS: "delete task success"
    , DELETE_TASK_FAILURE: "delete task failure"
    , TOGGLE_TASK: "toggle task"
    , TOGGLE_TASK_SUCCESS: "toggle task success"
    , TOGGLE_TASK_FAILURE: "toggle task failure"
    , UPDATE_DRAGGING_SOURCE: "update dragging source"
}